gmodified:   ts/bin/bt 	gnew file:   ts/build/kernel/dependencies_package/devstation 	gmodified:   ts/build/packages/base/bin/update-initrd 	gmodified:   ts/build/packages/devstation/bin/devcmd 	gmodified:   ts/build/packages/devstation/dependencies 	gmodified:   ts/ports/components/libnl3/.footprint 	gmodified:   ts/ports/components/libnl3/.md5sum 	gmodified:   ts/ports/components/libnl3/Pkgfile 	gdeleted:    ts/ports/components/libnl3/libnl3#3.2.25-1.pkg.tar.xz 	gnew file:   ts/ports/components/libnl3/libnl3#3.5.0-1.pkg.tar.xz 	gmodified:   ts/ports/components/libvirt/.footprint 	gmodified:   ts/ports/components/libvirt/.md5sum 	gmodified:   ts/ports/components/libvirt/Pkgfile 	gdeleted:    ts/ports/components/libvirt/libvirt#5.6.0-1.pkg.tar.xz 	gnew file:   ts/ports/components/libvirt/libvirt#6.7.0-2.pkg.tar.xz 	gmodified:   ts/ports/components/virt-viewer/.footprint 	gmodified:   ts/ports/components/virt-viewer/.md5sum 	gmodified:   ts/ports/components/virt-viewer/Pkgfile 	gdeleted:    ts/ports/components/virt-viewer/virt-viewer#8.0-1.pkg.tar.xz 	gnew file:   ts/ports/components/virt-viewer/virt-viewer#9.0-1.pkg.tar.xz 	gnew file:   ts/ports/contrib/asciidoctor/.footprint 	gnew file:   ts/ports/contrib/asciidoctor/.md5sum 	gnew file:   ts/ports/contrib/asciidoctor/Pkgfile 	gnew file:   ts/ports/contrib/asciidoctor/asciidoctor#2.0.10-1.pkg.tar.xz 	gnew file:   ts/ports/contrib/ebtables/.footprint 	gnew file:   ts/ports/contrib/ebtables/.md5sum 	gnew file:   ts/ports/contrib/ebtables/Pkgfile 	gnew file:   ts/ports/contrib/ebtables/README 	gnew file:   ts/ports/contrib/ebtables/ebtables#2.0.11-1.pkg.tar.xz 	gnew file:   ts/ports/contrib/ebtables/ebtables-2.0.11-ebt-save.patch 	gnew file:   ts/ports/contrib/ebtables/ebtables-2.0.11-makefile.patch 	gnew file:   ts/ports/contrib/ebtables/ebtables-2.0.11-remove-stray-atsign.patch 	gnew file:   ts/ports/opt/dnsmasq/.footprint 	gnew file:   ts/ports/opt/dnsmasq/.md5sum 	gnew file:   ts/ports/opt/dnsmasq/Pkgfile 	gnew file:   ts/ports/opt/dnsmasq/README 	gnew file:   ts/ports/opt/dnsmasq/dnsmasq 	gnew file:   ts/ports/opt/dnsmasq/dnsmasq#2.82-1.pkg.tar.xz 	gnew file:   ts/ports/opt/dnsmasq/dnsmasq-config.patch 	gmodified:   ts/ports/opt/qemu/.footprint 	gmodified:   ts/ports/opt/qemu/.md5sum 	gmodified:   ts/ports/opt/qemu/Pkgfile 	gmodified:   ts/ports/opt/qemu/qemu#git-1.pkg.tar.xz 	gnew file:   ts/ports/opt/qemu/rst-pygments.patch 	gmodified:   ts/ports/opt/wireshark/.footprint 	gmodified:   ts/ports/opt/wireshark/.md5sum 	gmodified:   ts/ports/opt/wireshark/Pkgfile 	grenamed:    ts/ports/opt/wireshark/wireshark#3.0.5-1.pkg.tar.xz -> ts/ports/opt/wireshark/wireshark#3.2.7-1.pkg.tar.xz

diff --git a/ts/bin/bt b/ts/bin/bt
--- a/ts/bin/bt
+++ b/ts/bin/bt
@@ -1,22 +1,35 @@
 #!/bin/bash
 set -x
-set -e
+#set -e
 
-#ISO=build/boot-images/refind-iso/thinstation-refind.iso
-ISO=build/boot-images/systemd-boot-iso/thinstation-efi.iso
-#ISO=build/boot-images/iso/thinstation.iso
-#ISO=eboot.iso
-#IMAGE=refind
-IMAGE=systemd-boot
-HD=thinstation.img
 procs=`nproc`
 let procs=procs/2
 
+confirm_edk2()
+{
+	if [ ! -e "usr/share/edk2.git/ovmf-x64/OVMF-pure-efi.fd" ]; then
+		echo "edk2 is not installed"
+		echo 'Please do a `prt-get install edk2 -im -if` inside the chroot environment and try again'
+		exit 1
+	fi
+}
+
 confirm_iso()
 {
+	case $1 in
+		systemd) ISO=build/boot-images/systemd-boot-iso/thinstation-efi.iso ;;
+		refind) ISO=build/boot-images/refind-iso/thinstation-refind.iso ;;
+	esac
+	if [ ! = $ISO ]; then
+		"$1 ISO $ISO"
+		"Not Found!"
+		exit 1
+	fi
+	CDROM="-drive file=$ISO,if=ide,media=cdrom,readonly"
 	if [ ! -e $ISO ]; then
 		echo "ISO not found: $ISO"
-		exit 1
+		echo "Did you build and ISO image?"
+		exit 2
 	fi
 }
 
@@ -24,6 +37,11 @@ confirm_hd()
 {
 	if [ ! -e $HD ]; then
 		qemu-img create -f qcow2 thinstation.img 31G
+	        if [ "$?" != "0" ]; then
+
+			echo "Likely not enought space to create hd image."
+			exit 3
+	fi
 	fi
 }
 
@@ -31,47 +49,151 @@ bridge()
 {
 	if [ -n "`ifconfig |grep -e br0`" ]; then
 		echo "-net bridge,br=br0 -net nic,macaddr=52:54:00:12F:34f:56 -netdev user,dns=8.8.8.8"
+#	else
+#		echo "-netdev user,id=n1 -device e1000,netdev=n1 -netdev tap,id=n2 -device virtio-net,netdev=n2"
 	fi
 }
 
-wrap_efi()
+wrap_systemd_efi()
 {
-#	cp $ISO $HD
-	export AGREE=true; mkgptdrv -o /build/boot-images/$IMAGE -p ESP:1G:boot -l thinstation.img:2G
-#	export AGREE=true; mkgptdrv -o /eb -p ESP:1G:boot -l thinstation.img:2G
+	if [ ! -e build/boot-images/systemd-boot ]; then
+		echo "$IMAGE not found?"
+		echo "Did you build an systemd image."
+		exit 1
+	fi
+	export AGREE=true
+	ts/bin/mkgptdrv -o build/boot-images/systemd-boot -p ESP:1G:boot -l thinstation.img:2G
+        if [ "$?" != "0" ]; then
+		echo "Likely not enough space to create systemd EFI hd qemu image."
+		exit 4
+	fi
+}
+
+wrap_refind_efi()
+{
+	if [ ! -e build/boot-images/refind ]; then
+                echo "refind image not found?"
+                echo "Did you build an refind image."
+                exit 1
+        fi
+        export AGREE=true
+	ts/bin/mkgptdrv -o build/boot-images/refind -p ESP:1G:boot -l thinstation.img:2G
+	if [ "$?" != "0" ]; then
+		echo "Likely not enough space to create refind EFI hd qemu image."
+		exit 5
+	fi
 }
 
 wrap_bios()
 {
-	export AGREE=true; mkmbrdrv -o /build/boot-images/syslinux -p d:1G:boot -l thinstation.img:2G
+	if [ ! -e build/boot-images/syslinux ]; then
+                echo "syslinux image not found."
+                echo "Did you build and image?"
+                exit 1
+        fi
+	export AGREE=true
+	ts/bin/mkmbrdrv -o build/boot-images/syslinux -p d:1G:boot -l thinstation.img:2G
+	if [ "$?" != "0" ]; then
+		echo "Likely not enought space to create syslinux qemu hd image."
+		exit 6
+	fi
 }
 
-VGA="-vga qxl -global qxl-vga.vram_size=132710400"
-CDROM="-drive file=$ISO,if=ide,index=1,media=cdrom"
+setup_qemu()
+{
+HD=thinstation.img
 HDD="-drive file=$HD,index=0,media=disk,format=raw"
+VGA="-vga qxl -global qxl-vga.vram_size=132710400"
 #VGA="-vga virtio"
 #VGA="-vga std"
 #VGA="-vga cirrus"
 #VGA="-vga vmware"
 SOUND="-soundhw ac97"
 CPU="-smp cores=$procs,threads=1,sockets=1"
-MEMORY="-m 4096"
+MEMORY="-m 2048"
 #RNG="-object rng-random,id=RNG"
 MOUSE="-usb -device usb-tablet"
 KVM="-enable-kvm"
-EFI="-L . --bios /usr/share/edk2.git/ovmf-x64/OVMF-pure-efi.fd"
+EFI="-L . --bios usr/share/edk2.git/ovmf-x64/OVMF_CODE-pure-efi.fd"
 NETWORK=`bridge`
 #QEMU=qemu-system-i386
 QEMU=qemu-system-x86_64
 
 STANDARD_MACHINE="$SOUND $RNG $VGA $CPU $MEMORY $MOUSE $KVM $NETWORK"
+}
 
 case $1 in
-	cd)	confirm_iso && confirm_hd && $QEMU $STANDARD_MACHINE $CDROM $HDD --boot d ;;
-	hd-efi)	wrap_efi && $QEMU $STANDARD_MACHINE $EFI $HDD;;
-	hd)	wrap_bios && $QEMU $STANDARD_MACHINE $HDD;;
-	image)  confirm_iso && confirm_hd && $QEMU $STANDARD_MACHINE $CDROM $HDD;;
-	net)	$QEMU $STANDARD_MACHINE $EFI;;
-	cd-efi)	confirm_iso && $QEMU $STANDARD_MACHINE $CDROM $EFI ;; #--boot menu=on;;
+        hd)
+		wrap_bios && \
+		setup_qemu && \
+                $QEMU $STANDARD_MACHINE $HDD
+                echo "Exit code $?"
+	;;
+	hd-systemd)
+		confirm_edk2 && \
+		wrap_systemd_efi && \
+                setup_qemu && \
+		$QEMU $STANDARD_MACHINE $EFI $HDD
+		echo "Exit code $?"
+	;;
+	hd-refind)
+		confirm_edk2 && \
+		wrap_refind_efi && \
+                setup_qemu && \
+		$QEMU $STANDARD_MACHINE $EFI $HDD
+                echo "Exit code $?"
+	;;
+	net)
+                setup_qemu && \
+		$QEMU $STANDARD_MACHINE
+		echo "Exit code $?"
+	;;
+        net-efi)
+                setup_qemu && \
+                $QEMU $STANDARD_MACHINE $EFI
+		echo "Exit code $?"
+	;;
+        cd)
+		confirm_iso systemd && \
+                setup_qemu && \
+                $QEMU $STANDARD_MACHINE $CDROM --boot d,menu=on
+                echo "Exit code $?"
+	;;
+	cd-systemd)
+		confirm_edk2 && \
+		confirm_iso systemd && \
+                setup_qemu && \
+		$QEMU $STANDARD_MACHINE $CDROM $EFI --boot c,menu=on
+		echo "Exit code $?"
+	;;
+	cd-refind)
+		confirm_edk2 && \
+		confirm_iso refind && \
+                setup_qemu && \
+		$QEMU $STANDARD_MACHINE $CDROM $EFI --boot c,menu=on
+                echo "Exit code $?"
+	;;
+	image)
+                confirm hd && \
+                confirm_iso systemd && \
+                setup_qemu && \
+                $QEMU $STANDARD_MACHINE $CDROM $HDD --boot c,menu=on
+                echo "Exit code $?"
+	;;
+	image-systemd)
+		confirm_edk2 && \
+		confirm_hd && \
+		confirm_iso systemd && \
+                setup_qemu && \
+                $QEMU $STANDARD_MACHINE $CDROM $HDD $EFI --boot d,menu=on
+                echo "Exit code $?"
+	;;
+	image-refind)
+		confirm_edk2 && \
+		confirm_hd && \
+		confirm_iso systemd && \
+                setup_qemu && \
+                $QEMU $STANDARD_MACHINE $CDROM $HDD $EFI --boot d,menu=on
+                echo "Exit code $?"
+	;;
 esac
-
diff --git a/ts/build/packages/base/bin/update-initrd b/ts/build/packages/base/bin/update-initrd
--- a/ts/build/packages/base/bin/update-initrd
+++ b/ts/build/packages/base/bin/update-initrd
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-. $TS_GLOBAL
+. /etc/thinstation.global
 bootdir=/boot/boot
-
+set -x
 show_help()
 {
 echo "
@@ -14,6 +14,49 @@ echo "
 		-p --path	Copy from a user specified path
 "
                 exit 255
+}
+
+exit_everything_already_current()
+{
+	echo "Everything is Up to Date"
+	exit 0
+}
+
+exit_update_completed()
+{
+        echo "Update Complete"
+        exit 1
+}
+
+exit_failed_no_md5()
+{
+	echo "Could not check md5"
+	exit 2
+}
+
+exit_invalid_path()
+{
+	echo "Invalid Path or missing vmlinuz and initrd"
+        exit 3
+
+}
+
+exit_copy_failed()
+{
+	echo "Something went wrong a file copy. Either permissions or space."
+	exit 4
+}
+
+exit_transfer_failed()
+{
+	echo "Something went wrong with a download from the internet. Are you connected?"
+	exit 5
+}
+
+exit_unwind_failed()
+{
+	echo "Something went wrong with the unwind of the update archive. Possibly a space problem or lack of memory"
+	exit 6
 }
 
 init()
@@ -38,100 +81,110 @@ init $@
 case $METHOD in
 	LOCAL)
 		cd $bootdir
-		cp /thinstation/build/boot-images/initrd/image.md5 check.md5
+		cp --update /thinstation/build/boot-images/initrd/image.md5 check.md5 || \
+		exit_failed_no_md5
 		if ! md5sum -c check.md5 ; then
-			cp /thinstation/build/boot-images/initrd/initrd $bootdir/initrd
-			cp /thinstation/build/boot-images/initrd/vmlinuz $bootdir/vmlinuz
+			echo "Your installation is out of date. Performing the update"
+			cp -f /thinstation/build/boot-images/initrd/initrd initrd || \
+				exit_copy_failed
+			cp -f /thinstation/build/boot-images/initrd/vmlinuz vmlinuz || \
+				exit_copy_failed
 			if [ -e /thinstation/build/boot-images/initrd/lib.squash ]; then
-				cp /thinstation/build/boot-images/initrd/lib.squash $bootdir/lib.update
+				cp -f /thinstation/build/boot-images/initrd/lib.squash lib.update || \
+				exit_copy_failed
 			fi
-			echo "Update Complete"
-			echo UPDATE_STATUS=0 > /tmp/update.tmp
+			exit_update_completed
 		else
-			echo "Everything is Up to Date"
-			echo UPDATE_STATUS=1 > /tmp/update.tmp
-
+			exit_everything_already_current
 		fi
 	;;
 	SERVER)
 		cd $bootdir
-		tftp -g -l check.md5 -r boot/image.md5 -b $TFTP_BLOCKSIZE $SERVER_IP
+		tftp -g -l check.md5 -r boot/image.md5 -b $TFTP_BLOCKSIZE $SERVER_IP || \
+		exit_failed_no_md5
 		if ! md5sum -c check.md5 ; then
+                        echo "Your installation is out of date. Performing the update"
 			if [ -e initrd ]; then
 				rm -f initrd
 				rm -f vmlinuz
 			fi
-			tftp -g -l initrd -r boot/initrd -b $TFTP_BLOCKSIZE $SERVER_IP
-			tftp -g -l vmlinuz -r boot/vmlinuz -b $TFTP_BLOCKSIZE $SERVER_IP
-			tftp -g -l lib.update -r boot/lib.squash -b $TFTP_BLOCKSIZE $SERVER_IP
-			echo "Update Complete"
-			echo UPDATE_STATUS=0 > /tmp/update.tmp
+			tftp -g -l initrd -r boot/initrd -b $TFTP_BLOCKSIZE $SERVER_IP || \
+				exit_transfer_failed
+			tftp -g -l vmlinuz -r boot/vmlinuz -b $TFTP_BLOCKSIZE $SERVER_IP || \
+				exit_transfer_failed
+			tftp -g -l lib.update -r boot/lib.squash -b $TFTP_BLOCKSIZE $SERVER_IP || \
+				exit_transfer_failed
+			exit_update_completed
 		else
-			echo "Everything is Up to Date"
-			echo UPDATE_STATUS=1 > /tmp/update.tmp
+			exit_everything_already_current
 		fi
 	;;
         SH)
                 cd $bootdir
-                wget http://$SERVER_IP/boot/image.md5
+                wget http://$SERVER_IP/boot/image.md5 || \
+		exit_failed_no_md5
                 if ! md5sum -c check.md5 ; then
+			echo "Your installation is out of date. Performing the update"
                         if [ -e initrd ]; then
                                 rm -f initrd
                                 rm -f vmlinuz
                         fi
-                        wget http://$SERVER_IP/boot/initrd
-                        wget http://$SERVER_IP/boot/vmlinuz
-                        wget http://$SERVER_IP/boot/lib.squash lib.update
-                        echo "Update Complete"
-                        echo UPDATE_STATUS=0 > /tmp/update.tmp
+                        wget http://$SERVER_IP/boot/initrd || \
+				exit_transfer_failed
+                        wget http://$SERVER_IP/boot/vmlinuz || \
+				exit_transfer_failed
+                        wget http://$SERVER_IP/boot/lib.squash lib.update || \
+				exit_transfer_failed
+			exit_update_completed
                 else
-                        echo "Everything is Up to Date"
-                        echo UPDATE_STATUS=1 > /tmp/update.tmp
+			exit_everything_already_current
                 fi
 
 	;;
 	WEB)
 		cd /tmp
-		wget ${WEBUPDATEROOT}/image-$TS_VERSION.md5 -O check.md5
+		wget ${WEBUPDATEROOT}/image-$TS_VERSION.md5 -O check.md5 || \
+		exit_failed_no_md5
 		cd $bootdir
 		if ! md5sum -c /tmp/check.md5 ; then
+			echo "Your installation is out of date. Performing the update"
 			cd /tmp
 			echo "Downloading a Default Image"
-			wget ${WEBUPDATEROOT}/thindev-default-$TS_VERSION.tar.xz
+			wget ${WEBUPDATEROOT}/thindev-default-$TS_VERSION.tar.xz || \
+				exit_transfer_failed
 			cd $bootdir
-			tar -xvf /tmp/thindev-default-$TS_VERSION.tar.xz
+			tar -xvf /tmp/thindev-default-$TS_VERSION.tar.xz || \
+				exit_unwind_failed
 			rm /tmp/thindev-default-$TS_VERSION.tar.xz
-			echo "Update Complete"
-			echo UPDATE_STATUS=0 > /tmp/update.tmp
+			exit_update_completed
 		else
-			echo "Everything is up to date"
-			echo UPDATE_STATUS=1 > /tmp/update.tmp
+			exit_everything_already_current
 		fi
 	;;
 	PATH)
 		if [ -e $LPATH/image.md5 ] ;then
-			cp $LPATH/image.md5 $bootdir/check.md5
 			cd $bootdir
+			cp --update $LPATH/image.md5 check.md5
 			if ! md5sum -c check.md5 ; then
+				echo "Your installation is out of date. Performing the update"
 				if [ -e $LPATH/initrd ] && [ -e $LPATH/vmlinuz ]; then
-	       	 			cp $LPATH/initrd $bootdir/initrd
-	        			cp $LPATH/vmlinuz $bootdir/vmlinuz
+	       	 			cp --update $LPATH/initrd initrd || \
+						exit_copy_failed
+	        			cp --update $LPATH/vmlinuz vmlinuz || \
+						exit_copy_failed
 	  		      		if [ -e $LPATH/lib.squash ]; then
-	                			cp $LPATH/lib.squash $bootdir/lib.update
+	                			cp --update $LPATH/lib.squash lib.update || \
+						exit_copy_failed
 					fi
-					echo "Update Complete"
-					echo UPDATE_STATUS=0 > /tmp/update.tmp
+					exit_update_completed
 				else
-					echo "Invalid Path or missing vmlinuz and initrd"
-					echo UPDATE_STATUS=3 > /tmp/update.tmp
+					exit_invalid_path
 				fi
 			else
-				echo "Everything is up to date"
-				echo UPDATE_STATUS=1 > /tmp/update.tmp
+				exit_everything_already_current
 			fi
 		else
-			echo "Could not check md5"
-			echo UPDATE_STATUS=2 > /tmp/update.tmp
+			exit_failed_no_md5
 		fi
 	;;
 esac
