modified:   ts/bin/bt

diff --git a/ts/bin/bt b/ts/bin/bt
--- a/ts/bin/bt
+++ b/ts/bin/bt
@@ -2,6 +2,24 @@
 set -x
 set -e
 
+ISO=build/boot-images/iso/thinstation.iso
+HD=thinstation.img
+
+confirm_iso()
+{
+	if [ ! -e $ISO ]; then
+		echo "ISO not found: $ISO"
+		exit 1
+	fi
+}
+
+confirm_hd()
+{
+	if [ ! -e $HD ]; then
+		qemu-img create -f qcow2 thinstation.img 30G
+	fi
+}
+
 #VGA="-vga qxl -global qxl-vga.vram_size=132710400"
 #VGA="-vga virtio"
 VGA="-vga vmware"
@@ -20,9 +38,9 @@ QEMU=qemu-system-x86_64
 STANDARD_MACHINE="$SOUND $RNG $VGA $CPU $MEMORY $MOUSE $KVM $NETWORK"
 
 case $1 in
-	cd)	$QEMU $STANDARD_MACHINE -cdrom build/boot-images/iso/thinstation.iso -hda thinstation.img --boot d;;
+	cd)	confirm_iso && confirm_hd && $QEMU $STANDARD_MACHINE -cdrom $ISO -hda $HD --boot d;;
 	bios)	$QEMU $STANDARD_MACHINE -hda build/bios.boot;;
-	image)  $QEMU $STANDARD_MACHINE -cdrom build/boot-images/iso/thinstation.iso -hda thinstation.img;;
-	*)	$QEMU $STANDARD_MACHINE -cdrom build/boot-images/iso/thinstation.iso $EFI;;
+	image)  confirm_iso && confirm_hd && $QEMU $STANDARD_MACHINE -cdrom $ISO -hda $HD;;
+	*)	confirm_iso && $QEMU $STANDARD_MACHINE -cdrom $ISO $EFI;;
 esac
 
