modified:   ts/TS_ENV 	new file:   ts/bin/404 	modified:   ts/bin/check_xorg 	modified:   ts/bin/clean_chroot 	modified:   ts/bin/install_chroot 	modified:   ts/bin/shrink 	modified:   ts/build/packages/dig/.dna 	modified:   ts/build/packages/evince/.dna 	modified:   ts/build/packages/installer/.dna 	modified:   ts/build/packages/installer/bin/install.sh 	modified:   ts/build/packages/introspection/.dna 	modified:   ts/build/packages/nfs/.dna 	modified:   ts/build/packages/ping/.dna 	modified:   ts/build/packages/xorg7-glamor/.dna 	renamed:    ts/build/packages/pcmcia/.dna -> ts/build/relegated/pcmcia/.dna 	renamed:    ts/build/packages/pcmcia/dependencies -> ts/build/relegated/pcmcia/dependencies 	renamed:    ts/build/packages/pcmcia/etc/pcmcia/config -> ts/build/relegated/pcmcia/etc/pcmcia/config 	renamed:    ts/build/packages/pcmcia/etc/pcmcia/network -> ts/build/relegated/pcmcia/etc/pcmcia/network 	renamed:    ts/build/packages/pcmcia/etc/pcmcia/wlags49.conf -> ts/build/relegated/pcmcia/etc/pcmcia/wlags49.conf 	modified:   ts/etc/pkgmk.conf 	modified:   ts/etc/prt-get.conf 	modified:   ts/unwind_cache/dig.turbo 	modified:   ts/unwind_cache/dnscrypt.turbo 	modified:   ts/unwind_cache/evince.turbo 	modified:   ts/unwind_cache/gdk-pixbuf.turbo 	modified:   ts/unwind_cache/installer.turbo 	modified:   ts/unwind_cache/introspection.turbo 	modified:   ts/unwind_cache/iphone.turbo 	modified:   ts/unwind_cache/kismet.turbo 	modified:   ts/unwind_cache/nfs.turbo 	deleted:    ts/unwind_cache/pcmcia.turbo 	modified:   ts/unwind_cache/ping.turbo 	deleted:    ts/unwind_cache/systemdnet.turbo 	deleted:    ts/unwind_cache/vmviewpcoip.turbo 	modified:   ts/unwind_cache/xorg7-glamor.turbo 	deleted:    ts/unwind_cache/xorg7_nvidia_64.turbo 	modified:   ts/unwind_cache/zoneinfo.turbo 	modified:   ts/wind_cache/dig.turbo 	modified:   ts/wind_cache/evince.turbo 	modified:   ts/wind_cache/gdk-pixbuf.turbo 	modified:   ts/wind_cache/installer.turbo 	modified:   ts/wind_cache/introspection.turbo 	modified:   ts/wind_cache/iphone.turbo 	modified:   ts/wind_cache/nfs.turbo 	deleted:    ts/wind_cache/pcmcia.turbo 	modified:   ts/wind_cache/ping.turbo 	deleted:    ts/wind_cache/systemdnet.turbo 	deleted:    ts/wind_cache/vmviewpcoip.turbo 	modified:   ts/wind_cache/xorg7-glamor.turbo 	deleted:    ts/wind_cache/xorg7_nvidia_64.turbo

diff --git a/ts/bin/install_chroot b/ts/bin/install_chroot
--- a/ts/bin/install_chroot
+++ b/ts/bin/install_chroot
@@ -53,7 +53,7 @@ stage2()
 	let procs-=1
 	for Root in $ROOT/ts $XTRWRKNG; do
 		find -L $Root/ports -name Pkgfile | \
-		grep -Ev "proprietary|binary-core|binary-opt" | \
+		grep -Ev "nocache|proprietary|binary-core|binary-opt|relegated" | \
 		grep -Ev "$exclude" | \
 		xargs -n 1 -P $procs -I {} bash -c 'install_port "$@"' _ {}
 	done
@@ -63,7 +63,9 @@ stage2()
 	done
 	add_to_db
 	printf "\rPort Installation %-40s\n" "Complete"
+	printf "\rRunning the pre and post install scripts\n"
 	post_install
+	printf "\rPort Install scripts %-40s\n" "Complete"
 	rm /dostage2
 	touch /dostage3
 }
@@ -180,10 +182,12 @@ install_port()
 			echo $version-$release >> /tmp/$name.db
 			tar -hxvf $port_dir/$pkg_name -C / >> /tmp/$name.db 2>/dev/null #|| rm /tmp/$name.db && echo "$pkg_name failed"
 			if [ -e $port_dir/pre-install ]; then
-				echo ". $port_dir/pre-install" >> $ROOT/post-install.sh
+#				echo "echo $port_name pre" >> $ROOT/post-install.sh
+				echo ". $port_dir/pre-install || echo \"$port_name pre-install failed!\" && true" >> $ROOT/post-install.sh
 			fi
 			if [ -e $port_dir/post-install ]; then
-				echo ". $port_dir/post-install" >> $ROOT/post-install.sh
+#				echo "echo $port_name post" >> $ROOT/post-install.sh
+				echo ". $port_dir/post-install || echo \"$port_name post-install failed!\" && true" >> $ROOT/post-install.sh
 			fi
 			return 0
 		else
