Modified profile to check the result of the last session in case x failed to run 	modified:   profile

diff --git a/ts/5.1/packages/base/etc/profile b/ts/5.1/packages/base/etc/profile
--- a/ts/5.1/packages/base/etc/profile
+++ b/ts/5.1/packages/base/etc/profile
@@ -12,8 +12,15 @@ if [ "$TERM" == "xinit" ] ; then
 			cp -a /etc/skel/$file $HOME/. 2>/dev/null
 		done
 	fi
-	/etc/xserverrc
-	exec /etc/xinitrc 2>&1 >> /var/run/applications/session.$$
+	check_last_session
+	exec xinit /etc/xinitrc -- /etc/xserverrc 2>&1 >> /var/run/applications/session.$$
+	error=$?
+	if [ "$error" != "0" ]; then
+		echo "Something went wrong! Starting the shell instead"
+		echo "exit code was $error"
+	else
+		exit $error
+	fi
 fi
 
 alias ll='ls -l'
