Added an md5 checksum routine to update-initrd 	modified:   ts/5.0/build 	modified:   ts/5.0/packages/base/bin/update-initrd 	modified:   ts/5.0/packages/devstation/bin/devcmd 	modified:   ts/bin/clean_chroot

diff --git a/ts/5.0/packages/base/bin/update-initrd b/ts/5.0/packages/base/bin/update-initrd
--- a/ts/5.0/packages/base/bin/update-initrd
+++ b/ts/5.0/packages/base/bin/update-initrd
@@ -7,54 +7,103 @@ init()
 LPATH=""
         until [ -z "$1" ] ; do
 		case $1 in
-			-p|--path)	LPATH="$2" ;;
-			-l|--local)     LOCAL="1" ;;
-			-h|--help)	HELP="1" ;;
-			-w|--web)	WEB="1" ;;
-			-s|--server)	SERVER="1" ;;
-			*)		echo "Invalid Option: $1" ;;
+			-p|--path)	METHOD=PATH LPATH="$2" ;;
+			-l|--local)     METHOD=LOCAL ;;
+			-h|--help)	METHOD=HELP ;;
+			-w|--web)	METHOD=WEB ;;
+			-s|--server)	METHOD=SERVER ;;
+			*)		echo "Invalid Option: $1" ; exit 255 ;;
                 esac
 		shift $#
 	done
 }
 init $@
 
-if [ "$LOCAL" == "1" ]; then
-	cp /thinstation/ts/5.0/boot-images/initrd/initrd /boot/initrd
-	cp /thinstation/ts/5.0/boot-images/initrd/vmlinuz /boot/vmlinuz
-	if [ -e /thinstation/ts/5.0/boot-images/initrd/lib.squash ]; then
-		cp /thinstation/ts/5.0/boot-images/initrd/lib.squash /boot/lib.update
-	fi
-elif [ "$SERVER" == "1" ]; then
-	cd /boot
-	if [ -e initrd ]; then
-		rm initrd
-		rm vmlinuz
-	fi
-	tftp -g -l initrd -r initrd -b $TFTP_BLOCKSIZE $SERVER_IP
-	tftp -g -l vmlinuz -r vmlinuz -b $TFTP_BLOCKSIZE $SERVER_IP
-	tftp -g -l lib.update -r lib.squash -b $TFTP_BLOCKSIZE $SERVER_IP
-elif [ "$WEB" == "1" ]; then
-	cd /tmp
-        echo "Downloading a Default Image"
-        wget http://www.doncuppjr.net/thindev-default.tar.xz
-	cd /boot
-        tar -xvf /tmp/thindev-default.tar.xz
-        rm /tmp/thindev-default.tar.xz
-elif [ "$LPATH" != "" ]; then
-	if [ -e $LPATH/initrd ] && [ -e $LPATH/vmlinuz ]; then
-	        cp $LPATH/initrd /boot/initrd
-	        cp $LPATH/vmlinuz /boot/vmlinuz
-	        if [ -e $LPATH/lib.squash ]; then
-	                cp $LPATH/lib.squash /boot/lib.update
+case $METHOD in
+	LOCAL)
+		cd /boot
+		cp /thinstation/ts/5.0/boot-images/initrd/image.md5 check.md5
+		if ! md5sum -c check.md5 ; then
+			cp /thinstation/ts/5.0/boot-images/initrd/initrd /boot/initrd
+			cp /thinstation/ts/5.0/boot-images/initrd/vmlinuz /boot/vmlinuz
+			if [ -e /thinstation/ts/5.0/boot-images/initrd/lib.squash ]; then
+				cp /thinstation/ts/5.0/boot-images/initrd/lib.squash /boot/lib.update
+			fi
+			echo "Update Complete"
+			exit 0
+		else
+			echo "Everything is Up to Date"
+			exit 1
 		fi
-	else
-		echo "Invalid Path or missing vmlinuz and initrd"
-	fi
-else
-	echo "	Usage:	-l	Copy from the local build env"
-	echo "		-s	Download from the dhcp assigned tftp server"
-	echo "		-w	Download the default image from the web"
-	echo "		-p	Copy from a user specified path"
-	echo "							"
-fi
+	;;
+	SERVER)
+		cd /boot
+		tftp -g -l check.md5 -r image.md5 -b $TFTP_BLOCKSIZE $SERVER_IP
+		if ! md5sum -c check.md5 ; then
+			if [ -e initrd ]; then
+				rm initrd
+				rm vmlinuz
+			fi
+			tftp -g -l initrd -r initrd -b $TFTP_BLOCKSIZE $SERVER_IP
+			tftp -g -l vmlinuz -r vmlinuz -b $TFTP_BLOCKSIZE $SERVER_IP
+			tftp -g -l lib.update -r lib.squash -b $TFTP_BLOCKSIZE $SERVER_IP
+			echo "Update Complete"
+			exit 0
+		else
+			echo "Everything is Up to Date"
+			exit 1
+		fi
+	;;
+	WEB)
+		cd /tmp
+		wget http://www.doncuppjr.net/image.md5 -O check.md5
+		cd /boot
+		if ! md5sum -c /tmp/check.md5 ; then
+			cd /tmp
+			echo "Downloading a Default Image"
+			wget http://www.doncuppjr.net/thindev-default.tar.xz
+			cd /boot
+			tar -xvf /tmp/thindev-default.tar.xz
+			rm /tmp/thindev-default.tar.xz
+			echo "Update Complete"
+			exit 0
+		else
+			echo "Everything is up to date"
+			exit 1
+		fi
+	;;
+	PATH)
+		if [ -e $LPATH/image.md5 ] ;then
+			cp $LPATH/image.md5 /boot/check.md5
+			cd /boot
+			if ! md5sum -c check.md5 ; then
+				if [ -e $LPATH/initrd ] && [ -e $LPATH/vmlinuz ]; then
+	       	 			cp $LPATH/initrd /boot/initrd
+	        			cp $LPATH/vmlinuz /boot/vmlinuz
+	  		      		if [ -e $LPATH/lib.squash ]; then
+	                			cp $LPATH/lib.squash /boot/lib.update
+					fi
+					echo "Update Complete"
+					exit 0
+				else
+					echo "Invalid Path or missing vmlinuz and initrd"
+					exit 3
+				fi
+			else
+				echo "Everything is up to date"
+				exit 1
+			fi
+		else
+			echo "Could not check md5"
+			exit 2
+		fi
+	;;
+	HELP)
+		echo "	Usage:	-l	Copy from the local build env"
+		echo "		-s	Download from the dhcp assigned tftp server"
+		echo "		-w	Download the default image from the web"
+		echo "		-p	Copy from a user specified path"
+		echo "							"
+		exit 255
+	;;
+esac
