new file:   ts/bin/watchit 	modified:   ts/build/build.urls 	modified:   ts/build/packages/xorg7_nvidia/build/install 	modified:   ts/build/packages/xorg7_nvidia_64/build/install

diff --git a/ts/build/packages/xorg7_nvidia/build/install b/ts/build/packages/xorg7_nvidia/build/install
--- a/ts/build/packages/xorg7_nvidia/build/install
+++ b/ts/build/packages/xorg7_nvidia/build/install
@@ -7,12 +7,8 @@ release=${release%TS}
 
 
 INSTALLDIR="/build/packages/xorg7_nvidia"
-DROP_FILES="nvidia-bug-report.sh nvidia-cuda-mps-control nvidia-cuda-mps-server nvidia-debugdump nvidia-installer nvidia-persistenced nvidia-smi nvidia-uninstall \
-libEGL.so.1 libGLESv1_CM.so.$version libOpenCL.so.1.0.0 libnvidia-cfg.so.1 libnvidia-encode.so.$version libnvidia-ifr.so.1 libnvidia-opencl.so.$version \
-libEGL.so.$version libGLESv2.so.2 libcuda.so.1 libnvidia-cfg.so.$version libnvidia-fbc.so.1 libnvidia-ifr.so.$version libGLESv2.so.$version libcuda.so.$version \
-libnvidia-compiler.so.$version libnvidia-fbc.so.$version libOpenCL.so.1 libnvidia-eglcore.so.$version libGLESv1_CM.so.1 libOpenCL.so.1.0 libnvidia-encode.so.1 \
-libnvidia-opencl.so.1 libglx.so libGL.so.1 libnvcuvid.so.$version libnvidia-glsi.so.$version libnvidia-ml.so.$version libnvcuvid.so.1 libnvidia-ml.so.1 libGL.la \
-libnvidia-wfb.so.1 libnvidia-wfb.so.$version libnvidia-gtk3.so.$version libEGL_nvidia.so.$version libEGL_nvidia.so.0 libnvidia-egl-wayland.so.$version"
+
+DROP_FILES="libGL.la libnvidia-egl-wayland.so.1.0.2"
 
 KMOD=kernel/drivers/video
 
@@ -20,40 +16,63 @@ cd wget_tmp
 sh $gzname -x
 cd NVIDIA-Linux-x86-$version
 
-./nvidia-installer -s -z -k ${release} --no-x-check --no-runlevel-check --no-kernel-module --log-file-name=./nvidia-installer.log --utility-prefix=$INSTALLDIR --documentation-prefix=$INSTALLDIR --opengl-prefix=$INSTALLDIR --x-library-path=$INSTALLDIR/lib --x-module-path=$INSTALLDIR/lib/xorg/modules --application-profile-path=$INSTALLDIR/lib/nvidia --no-nvidia-modprobe
+./nvidia-installer -s -z -k ${release} --no-x-check --no-kernel-module --log-file-name=./nvidia-installer.log --utility-prefix=$INSTALLDIR --documentation-prefix=$INSTALLDIR --opengl-prefix=$INSTALLDIR --x-library-path=$INSTALLDIR/lib --x-module-path=$INSTALLDIR/lib/xorg/modules --application-profile-path=$INSTALLDIR/lib/nvidia --no-nvidia-modprobe
 
 mkdir -p $INSTALLDIR/lib/licenses/nvidia
-mv $INSTALLDIR/share/doc/NVIDIA_GLX-1.0/LICENSE $INSTALLDIR/lib/licenses/nvidia/.
+  mv $INSTALLDIR/share/doc/NVIDIA_GLX-1.0/LICENSE $INSTALLDIR/lib/licenses/nvidia/.
 mkdir -p $INSTALLDIR/lib/icons/hicolor/48x48/apps
-mv $INSTALLDIR/share/doc/NVIDIA_GLX-1.0/nvidia-settings.png $INSTALLDIR/lib/icons/hicolor/48x48/apps/.
+  mv $INSTALLDIR/share/doc/NVIDIA_GLX-1.0/nvidia-settings.png $INSTALLDIR/lib/icons/hicolor/48x48/apps/.
+rm -rf $INSTALLDIR/share
 
 mkdir -p $INSTALLDIR/lib/applications
-if [ -e /usr/local/share/applications/nvidia-settings.desktop ]; then
-  mv /usr/local/share/applications/nvidia-settings.desktop $INSTALLDIR/lib/applications
-elif [ -e $INSTALLDIR/share/applications ]; then
-  mv $INSTALLDIR/share/applications/* $INSTALLDIR/lib/applications
-fi
+  mv /usr/local/share/applications/nvidia-settings.desktop		$INSTALLDIR/lib/applications
+mkdir -p $INSTALLDIR/etc/X11
+  mv /usr/share/X11/xorg.conf.d/nvidia-drm-outputclass.conf		$INSTALLDIR/etc/X11
+mkdir -p $INSTALLDIR/lib/glvnd/egl_vendor.d
+  mv /usr/share/glvnd/egl_vendor.d/10_nvidia.json			$INSTALLDIR/lib/glvnd/egl_vendor.d
+mkdir -p $INSTALLDIR/lib/egl/egl_external_platform.d
+  mv /usr/share/egl/egl_external_platform.d/10_nvidia_wayland.json	$INSTALLDIR/lib/egl/egl_external_platform.d
 
-mv /usr/share/nvidia/* $INSTALLDIR/lib/nvidia
+for link in `find $INSTALLDIR/lib -mindepth 1 -maxdepth 1 -type l | grep -E '\.so' | sort -u`; do
+	# Normalize the link
+	if [ -h $link ]; then
+		linkdest=`readlink $link | sed -e 's,\.\./\.\./lib/,,' -e 's,^/lib/,,'`
+		linkdir=`dirname $link`
+		# If the link is to another directory, leave it alone
+		if [ `echo $linkdest | grep -E '/'` ]; then
+			continue
+		fi
 
-rm -rf $INSTALLDIR/share
+		soname=`objdump -p $linkdir/$linkdest | grep SONAME | awk '{print $2}'`
+		base=`basename $link`
+		if [ -z "$soname" ]; then
+			echo "MISSING SONAME $link"
+			exit 1
+		fi
+		if [ "$base" == "$soname" ]; then
+			rm $link
+			cp $linkdir/$linkdest $link
+			rm $linkdir/$linkdest
+		else
+			rm $link
+		fi
+	fi
+done
+
 for file in $DROP_FILES; do
 	find $INSTALLDIR -name $file -delete
 done
-find $INSTALLDIR -type l -name \*.so -delete
 
 cd kernel
 
 for kernel in TS TS_SMP; do
+	make SYSSRC=/usr/src/kernels/${release}${kernel} module
 	if [ -e /etc/ssl/keys/kernel.key ]; then
-		make SYSSRC=/usr/src/kernels/${release}${kernel} \
-			module \
-			module-sign \
-			MODSECKEY=/etc/ssl/keys/kernel.key \
-			MODPUBKEY=/etc/ssl/certs/kernel.crt
-	else
- 		make SYSSRC=/usr/src/kernels/${release}${kernel} \
-			module
+		/usr/src/kernels/${release}${kernel}/scripts/sign-file \
+			sha256 \
+			/etc/ssl/keys/kernel.key \
+			/etc/ssl/certs/kernel.crt \
+			nvidia.ko
 	fi
 	mkdir -p $INSTALLDIR/lib/modules/${release}${kernel}/$KMOD
 	cp -a nvidia.ko $INSTALLDIR/lib/modules/${release}${kernel}/$KMOD
@@ -65,7 +84,7 @@ rm -f /usr/share/kde-settings/kde-profile/default/share/applications/nvidia-sett
 
 cp -Prfd $INSTALLDIR/build/extra/* $INSTALLDIR/.
 
-#Fix libGL, because nvidia compile completely steps on everybody.
+# Fix libGL, because nvidia compile completely steps on everybody.
 
 glversion=`prt-get info mesa3d |grep -e Version |cut -c15-`
 gldir=`prt-get info mesa3d |grep -e Path |cut -c15-`
